// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd5t6WGYWCUHNLgJRot3EE7ys-WguS4Y4',
    appId: '1:618669650396:web:be2721e6b2fb341b039f19',
    messagingSenderId: '618669650396',
    projectId: 'fir-a548b',
    authDomain: 'fir-a548b.firebaseapp.com',
    storageBucket: 'fir-a548b.appspot.com',
    measurementId: 'G-Q0H4JZT7Z5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKAo9i1x8WMexs-G8VieUdu-kxvimT13o',
    appId: '1:618669650396:android:60e7518085042419039f19',
    messagingSenderId: '618669650396',
    projectId: 'fir-a548b',
    storageBucket: 'fir-a548b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ3jLMUmpL0LhYvLA6AjD-ZnM2opkgdvM',
    appId: '1:618669650396:ios:93888767583b064a039f19',
    messagingSenderId: '618669650396',
    projectId: 'fir-a548b',
    storageBucket: 'fir-a548b.appspot.com',
    iosBundleId: 'com.example.firebaseFirst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ3jLMUmpL0LhYvLA6AjD-ZnM2opkgdvM',
    appId: '1:618669650396:ios:93888767583b064a039f19',
    messagingSenderId: '618669650396',
    projectId: 'fir-a548b',
    storageBucket: 'fir-a548b.appspot.com',
    iosBundleId: 'com.example.firebaseFirst',
  );
}
